=== muralis54/web-opac/xml/add_books.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="books">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Title" type="xs:string" />
                            <xs:element name="ISBN" type="xs:string" />
                            <xs:element name="Name">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Author_First_Name" type="xs:string" />
                                        <xs:element name="Author_Middle_Name" />
                                        <xs:element name="Author_Last_Name" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Rating" type="xs:string" />
                            <xs:element name="Publisher" type="xs:string" />
                            <xs:element name="Category" type="xs:string" />
                            <xs:element name="Quantity" type="xs:string" />
                            <xs:element name="Date" type="xs:string" />
                            <xs:element name="currency_symbols" type="xs:string" />
                            <xs:element name="Price" type="xs:string" />
                            <xs:element name="Copyright">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="year" type="xs:string" />
                                        <xs:element name="Owner_Name" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== muralis54/web-opac/xml/add_books.xml
<?xml version = '1.0' encoding = 'utf-8'?>

<books  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="add_books.xsd">
    <book id="1">
        <Title>Percy Jackson</Title>
        <ISBN>123dsa3f5</ISBN>
        <Name>
            <Author_First_Name>Rick</Author_First_Name>
            <Author_Middle_Name></Author_Middle_Name>
            <Author_Last_Name>Rioirdian</Author_Last_Name>
        </Name>
        <Rating>9</Rating>
        <Publisher>Potter Publisher</Publisher>
        <Category>Mystery</Category>
        <Quantity>5</Quantity>
        <Date>22.06.2000</Date>
        <currency_symbols>$</currency_symbols>
        <Price>100.5</Price>
        <Copyright>
            <year>2023</year>
            <Owner_Name>Sat Groups</Owner_Name>
        </Copyright>
    </book>
    <book id='2'>
        <Title>Harry Potter</Title>
        <ISBN>123dsa3f5</ISBN>
        <Name>
            <Author_First_Name>Rick</Author_First_Name>
            <Author_Middle_Name></Author_Middle_Name>
            <Author_Last_Name>Rioirdian</Author_Last_Name>
        </Name>
        <Rating>9</Rating>
        <Publisher>Potter Publisher</Publisher>
        <Category>Mystery</Category>
        <Quantity>5</Quantity>
        <Date>22.06.2000</Date>
        <currency_symbols>Â£</currency_symbols>
        <Price>10.2</Price>
        <Copyright>
            <year>2023</year>
            <Owner_Name>Sat Groups</Owner_Name>
        </Copyright>
    </book>
</books>
