=== muralis54/web-opac/xml/register.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="register_form">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="full_name" type="xs:string" />
                            <xs:element name="phone_number">
                                <xs:complexType mixed="true">
                                    <xs:sequence minOccurs="0">
                                        <xs:element name="p1" minOccurs="0" type="xs:string" />
                                        <xs:element name="p2" minOccurs="0" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="DOB" type="xs:string" />
                            <xs:element name="email" type="xs:string" />
                            <xs:element name="password" type="xs:string" />
                            <xs:element name="confirm_password" type="xs:string" />
                            <xs:element name="gender" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== muralis54/web-opac/xml/register.xml
<?xml version="1.0" encoding="UTF-8"?>

<register_form xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="register.xsd">
<user id='1'>
    <full_name>Murali S</full_name>
    <phone_number>
        <p1>7871151617</p1>
        <p2>8695234505</p2>
    </phone_number>
    <DOB>05-04-2001</DOB>
    <email>vasanthmurali3196@gmail.com</email>
    <password>sathya2206</password>
    <confirm_password>sathya2206</confirm_password>
    <gender>male</gender>
</user>
<user id='2'>
    <full_name>Sathya M</full_name>
    <phone_number>6383235037</phone_number>
    <DOB>22-06-2000</DOB>
    <email>sathya2206@gmail.com</email>
    <password>sathya@2206</password>
    <confirm_password>sathya@2206</confirm_password>
    <gender>female</gender>
</user>
</register_form>
